ifeq ($(PLATFORM),cm4)
dtbo-y += clockworkpi-uconsole-overlay.dtbo
endif

ifeq ($(PLATFORM),cm5)
dtbo-y += clockworkpi-uconsole-cm5-overlay.dtbo
endif

always-y := $(dtbo-y)

%.dtbo: %.dts
	$(CPP) -E -P -x assembler-with-cpp -I $(KDIR)/include -undef -D__DTS__ $< | \
		$(KDIR)/scripts/dtc/dtc -@ -I dts -O dtb -o $@ -
